{
 "title": "Container Monitor",
 "tags": [ "containermon" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application_name", "label": "Application", "query": "label_values(application_name)" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({application_name=\"$application_name\"},host)"
   }
  ]
 },
 "panels": [
  {
   "title": "General Information Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall Disk Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "disk_used_percent", "legendFormat": "{{application_name}}" }
     ]
    },
    {
     "title": "Overall RAM Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cgroup_memory_usage_in_bytes / cgroup_memory_limit_in_bytes * 100",
       "legendFormat": "{{application_name}}"
      }
     ]
    },
    {
     "title": "Overall CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(cpu_usage_system{cpu=\"cpu-total\"} + cpu_usage_user{cpu=\"cpu-total\"})",
       "legendFormat": "{{application_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "General Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RootFS Total",
     "type": "singlestat",
     "description": "Total RootFS",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "disk_total{application_name=\"$application_name\",host=\"$host\",path=\"-\"}"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "singlestat",
     "description": "Total RAM",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "cgroup_memory_limit_in_bytes{application_name=\"$application_name\",host=\"$host\"}"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "singlestat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(cpu_usage_system{application_name=\"$application_name\",host=\"$host\"}) - 1"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "disk_used_percent{application_name=\"$application_name\",host=\"$host\", path=\"-\"}"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "cgroup_memory_usage_in_bytes{application_name=\"$application_name\",host=\"$host\"} / cgroup_memory_limit_in_bytes{application_name=\"$application_name\",host=\"$host\"} * 100"
      }
     ]
    },
    {
     "title": "CPU Used",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(cpu_usage_system{host=\"$host\",application_name=\"$application_name\",cpu=\"cpu-total\"} + cpu_usage_user{host=\"$host\",application_name=\"$application_name\",cpu=\"cpu-total\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "disk_used_percent{application_name=\"$application_name\",host=\"$host\"}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "cgroup_memory_usage_in_bytes{application_name=\"$application_name\",host=\"$host\"} / cgroup_memory_limit_in_bytes{application_name=\"$application_name\",host=\"$host\"} * 100"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "cpu_usage_system{host=\"$host\",application_name=\"$application_name\",cpu=\"cpu-total\"} + cpu_usage_user{host=\"$host\",application_name=\"$application_name\",cpu=\"cpu-total\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time",
     "type": "graph",
     "description": "Response Time of port 8080",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "net_response_response_time{host=\"$host\", application_name=\"$application_name\"}"
      }
     ]
    },
    {
     "title": "Socket Connection States",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(netstat_tcp_close{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "TCP close"
      },
      {
       "expr": "(netstat_tcp_close_wait{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "TCP close wait"
      },
      {
       "expr": "(netstat_tcp_closing{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "TCP closing"
      },
      {
       "expr": "(netstat_tcp_established{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "TCP established"
      },
      {
       "expr": "(netstat_tcp_fin_wait1{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "TCP fin wait1"
      },
      {
       "expr": "(netstat_tcp_fin_wait2{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "TCP fin wait2"
      },
      {
       "expr": "(netstat_tcp_last_ack{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "TCP last ack"
      },
      {
       "expr": "(netstat_tcp_listen{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "TCP listen"
      },
      {
       "expr": "(netstat_tcp_none{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "TCP none"
      },
      {
       "expr": "(netstat_tcp_syn_recv{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "TCP syn recv"
      },
      {
       "expr": "(netstat_tcp_syn_sent{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "TCP syn sent"
      },
      {
       "expr": "(netstat_tcp_time_wait{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "TCP time wait"
      },
      {
       "expr": "(netstat_udp_socket{application_name=\"$application_name\", host=\"$host\"})",
       "legendFormat": "UDP socket"
      }
     ]
    },
    {
     "title": "Packages Received / Send",
     "type": "graph",
     "description": "Overview of Received and Send Packages in absolut values",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "net_packets_recv{host=\"$host\",application_name=\"$application_name\"} ",
       "legendFormat": "Packages Received"
      },
      {
       "expr": "net_packets_sent{host=\"$host\",application_name=\"$application_name\"} * - 1",
       "legendFormat": "Packages Send"
      }
     ]
    },
    {
     "title": "Bytes Received / Send",
     "type": "graph",
     "description": "Overview of Received and Send Bytes in absolut values",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "net_bytes_recv{application_name=\"$application_name\",host=\"$host\"}",
       "legendFormat": "Bytes Received"
      },
      {
       "expr": "net_bytes_sent{application_name=\"$application_name\",host=\"$host\"} * -1",
       "legendFormat": "Bytes Send"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "IP",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(net_ip_defaultttl{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "DefaultTTL"
      },
      {
       "expr": "irate(net_ip_forwarding{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "Forwarding"
      },
      {
       "expr": "irate(net_ip_forwdatagrams{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "ForwDatagrams"
      },
      {
       "expr": "irate(net_ip_fragcreates{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "FragCreates"
      },
      {
       "expr": "irate(net_ip_fragfails{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "FragFails"
      },
      {
       "expr": "irate(net_ip_fragoks{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "FragOKs"
      },
      {
       "expr": "irate(net_ip_inaddrerrors{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InAddrErrors"
      },
      {
       "expr": "irate(net_ip_indelivers{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InDelivers"
      },
      {
       "expr": "irate(net_ip_indiscards{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InDiscards"
      },
      {
       "expr": "irate(net_ip_inhdrerrors{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InHdrErrors"
      },
      {
       "expr": "irate(net_ip_inreceives{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InReceives"
      },
      {
       "expr": "irate(net_ip_inunknownprotos{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InUnknownProtos"
      },
      {
       "expr": "irate(net_ip_outdiscards{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "OutDiscards"
      },
      {
       "expr": "irate(net_ip_outnoroutes{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "OutNoRoutes"
      },
      {
       "expr": "irate(net_ip_outrequests{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "OutRequests"
      },
      {
       "expr": "irate(net_ip_reasmfails{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "ReasmFails"
      },
      {
       "expr": "irate(net_ip_reasmoks{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "ReasmOKs"
      },
      {
       "expr": "irate(net_ip_reasmreqds{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "ReasmReqds"
      },
      {
       "expr": "irate(net_ip_reasmtimeout{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "ReasmTimeout"
      }
     ]
    },
    {
     "title": "TCP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(net_tcp_activeopens{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "ActiveOpens"
      },
      {
       "expr": "irate(net_tcp_attemptfails{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "AttemptFails"
      },
      {
       "expr": "irate(net_tcp_currestab{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "CurrEstab"
      },
      {
       "expr": "irate(net_tcp_estabresets{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "EstabResets"
      },
      {
       "expr": "irate(net_tcp_incsumerrors{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InCsumErros"
      },
      {
       "expr": "irate(net_tcp_inerrs{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InErrs"
      },
      {
       "expr": "irate(net_tcp_insegs{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InSegs"
      },
      {
       "expr": "irate(net_tcp_maxconn{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "MaxConn"
      },
      {
       "expr": "irate(net_tcp_outrsts{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "OutRsts"
      },
      {
       "expr": "irate(net_tcp_outsegs{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "OutSegs"
      },
      {
       "expr": "irate(net_tcp_passiveopens{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "PassiveOpens"
      },
      {
       "expr": "irate(net_tcp_retranssegs{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "RetransSegs"
      },
      {
       "expr": "irate(net_tcp_rtoalgorithm{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "RtoAlgorithm"
      },
      {
       "expr": "irate(net_tcp_rtomax{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "RtoMax"
      },
      {
       "expr": "irate(net_tcp_rtomin{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "RtoMin"
      }
     ]
    },
    {
     "title": "UDP",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(net_udp_ignoredmulti{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "IgnoredMulti"
      },
      {
       "expr": "irate(net_udp_incsumerrors{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InCsumErrors"
      },
      {
       "expr": "irate(net_udp_indatagrams{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InDatagrams"
      },
      {
       "expr": "irate(net_udp_inerrors{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InErrors"
      },
      {
       "expr": "irate(net_udp_noports{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "NoPorts"
      },
      {
       "expr": "irate(net_udp_outdatagrams{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "OutDatagrams"
      },
      {
       "expr": "irate(net_udp_rcvbuferrors{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "RcvbufErrors"
      },
      {
       "expr": "irate(net_udp_sndbuferrors{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "SndbufErrors"
      }
     ]
    },
    {
     "title": "UDP LITE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(net_udplite_ignoredmulti{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "IgnoredMulti"
      },
      {
       "expr": "irate(net_udplite_incsumerrors{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InCsumErrors"
      },
      {
       "expr": "irate(net_udplite_indatagrams{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InDatagrams"
      },
      {
       "expr": "irate(net_udplite_inerrors{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "InErrors"
      },
      {
       "expr": "irate(net_udplite_noports{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "NoPorts"
      },
      {
       "expr": "irate(net_udplite_outdatagrams{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "OutDatagrams"
      },
      {
       "expr": "irate(net_udplite_rcvbuferrors{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "RcvbufErrors"
      },
      {
       "expr": "irate(net_udplite_sndbuferrors{application_name=~\"$application_name\",host=~\"$host\"}[5m])",
       "legendFormat": "SndbufErrors"
      }
     ]
    }
   ]
  }
 ]
}